<?php

namespace Tests\Unit\Repositories;

use App\Models\Post;
use App\Models\User;
use App\Repositories\PostRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PostRepositoryTest extends TestCase
{
    use RefreshDatabase;

    protected $postRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->postRepository = app(PostRepository::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_it_create_post_success()
    {
        $post =Post::factory()->make();
        $record = $this->postRepository->store($post->toArray());
        $this->assertDatabaseHas('posts',
            [
                'id' => data_get($record, 'id')
            ]
        );
    }


    public function test_it_get_single_post_with_comment_success()
    {
        $post =Post::factory()->make();
        $record = $this->postRepository->store($post->toArray());
        $this->assertDatabaseHas('posts',
            [
                'id' => data_get($record, 'id')
            ]
        );

        $this->postRepository->destroy(data_get($record,'id'));

        $this->assertDatabaseMissing('posts',
            [
                'id' => data_get($record, 'id')
            ]
        );
    }


    public function test_it_get_all_posts()
    {
        $count = 10;
        $posts =Post::factory($count)->make();

        foreach ($posts as $post) {
             $this->postRepository->store($post->toArray());
        }
        $this->assertDatabaseCount('posts', $count);
    }
}
